### ISSUE TITLE
Tree Definitions: externalview custom URLs blocked as popups (Firefox, Chrome)

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS-Foundation#176]
**Prepare**:
1. Use Chrome / Firefox. (IE11 & Edge are OK).
2. Create a tree definition file (.xml) in `~/App_Data/Composite/TreeDefinitions`.
3. Add the markup below.
4. Restart the server + Reload the C1 Console - if needed.

**Repro**:
1. In the "Content" perspective, click "Composite Tests".
2. Click "External URL Action" on the toolbar.

**Expected**: The URL opens in a new window / tab.
**Actual**: A popup gets blocked by the browser.

**The markup to use**:

```
<?xml version="1.0" encoding="UTF-8"?>
<ElementStructure xmlns="http://www.composite.net/ns/management/trees/treemarkup/1.0" 
xmlns:f="http://www.composite.net/ns/function/1.0">
    <ElementStructure.AutoAttachments>
        <NamedParent Name="Content" Position="Bottom"/>
    </ElementStructure.AutoAttachments>
    <ElementRoot>
        <Children>
            <Element Label="Composite Tests" Id="CompositeTestsId">
                <Actions>
                        <CustomUrlAction Label="External URL action" 
                        Url="http://www.composite.net" 
                        ViewType="externalview" />
                </Actions>
            </Element>
        </Children>
    </ElementRoot>
</ElementStructure>
```

**Comment by mawtex** [comment]
Fixed by @neexite in ed819e5

**Comment by wwwysocki** [comment]
Still reproducible in more specific cases:

**Case 1**: Chrome only

1. Do the steps as in the original report.
2. Click "External URL Action" several times. (Normally reproducible on the second click.)

**Case 2**: Chrome & Firefox only (not described before)

1. Double-click "Composite Tests".

In both cases, the popup gets blocked.

IE10 and Edge are OK.

(20160609.1_dev)

**Comment by mawtex** [comment]
I can't repro this issue, seems fixed.
